---
model_spec:
  name: clip
  pretrained: true
  audio_config:
    sample_rate: 16000
    n_fft: 800
    hop_length: 160
    win_length: 800
    window: hann
    n_mels: 128
    representation: mel_spectrogram
    normalize: false
    target_length_seconds: 10
    window_selection: random
  text_model_name: roberta-base
  projection_dim: 512
  temperature: 0.07
  audio_encoder_init_from: esp_aves2_effnetb0_all

dataset_config: configs/data_configs/clap/data_chain_animalspeak_audiosetcaps.yml

label_type: text

preprocessing: null
sr: 16000
debug_mode: false

logging: wandb
output_dir: "./runs/clap/clap_chain_animalspeak_audiosetcaps"

training_params:
  train_epochs: 50
  lr: 0.0001
  batch_size: 680
  optimizer: adamw8bit
  weight_decay: 0.01
  amp: true
  amp_dtype: bf16
  log_steps: 100
  gradient_checkpointing: true

scheduler:
  name: cosine
  warmup_steps: 500
  min_lr: 1e-6

augmentations:
  # Add background noise at random SNRs
  - noise:
      noise_dirs:
        - gs://foundation-model-data/audio_16k/noise_clean/demand_10s
        - gs://foundation-model-data/audio_16k/noise_clean/idmt
        - gs://foundation-model-data/audio_16k/noise_clean/tut2016_10s
        - gs://foundation-model-data/audio_16k/noise_clean/urbansound
        - gs://foundation-model-data/audio_16k/noise_clean/orcasound_shipnoise_10s
        - gs://foundation-model-data/audio_16k/noise_clean/deepship_10s
        - gs://foundation-model-data/audio_16k/noise_clean/shipsear_10s
        - gs://foundation-model-data/audio_16k/noise_clean/wham_noise
        - gs://foundation-model-data/audio_16k/noise_clean/audioset
        - gs://fewshot/data_large_clean/silentcities_sampled_big_filtered_cropped_16kHz_v1_plus_avex
        # - "/home/milad_earthspecies_org/data-migration/lambda/home/ubuntu/\
        #   foundation-model-storage/foundation-model-data/audio_16k/noise/\
        #   ssw-detection"
      snr_db_range: [-5, 20]  # mix noise between -5 dB and 20 dB SNR
      augmentation_prob: 0.5

loss_function: contrastive

device: cuda

seed: 13
num_workers: 18
run_name: clap_chain_animalspeak_audiosetcaps
wandb_project: avex
